"""globals.py: Used to share global variables between submodules."""

global H_FLIP, V_FLIP
global FORCE_IMAGE_GENERATION, FORCE_MAP_DATA_GENERATION
global NAMESPACE, NAMESPACE_UNDERSCORE, NAMESPACE_COLON
global PARSE_BOUNDARIES, PARSE_ACTORS
global CREATE_GLOBALS_FILE

H_FLIP = 1024
V_FLIP = 2048

FORCE_IMAGE_GENERATION = False
FORCE_MAP_DATA_GENERATION = False
NAMESPACE = ""
NAMESPACE_UNDERSCORE = ""
NAMESPACE_COLON = ""
PARSE_BOUNDARIES = False
PARSE_ACTORS = False
CREATE_GLOBALS_FILE = False